name: NODE APP

on: push

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
    - name: Welcome message
      run: echo "hello"
    
    - name: list files
      run: ls

    - name: readme file
      run: cat readme.md

